apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: config-server
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: config-server
      app.kubernetes.io/part-of: petclinic
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: discovery-server
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: discovery-server
      app.kubernetes.io/part-of: petclinic
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customers-service
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: customers-service
      app.kubernetes.io/part-of: petclinic
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: visits-service
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: visits-service
      app.kubernetes.io/part-of: petclinic
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vets-service
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vets-service
      app.kubernetes.io/part-of: petclinic
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: genai-service
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: genai-service
      app.kubernetes.io/part-of: petclinic
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/part-of: petclinic
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: admin-server
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-server
      app.kubernetes.io/part-of: petclinic
