apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Goodnessoj/petclinic-Infra.git
    targetRevision: main
    path: argocd
    directory:
      exclude: application.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
