apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: petclinic-services
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: config-server
            valuesFile: config-server.yaml
          - name: discovery-server
            valuesFile: discovery-server.yaml
          - name: api-gateway
            valuesFile: api-gateway.yaml
          - name: customers-service
            valuesFile: customers-service.yaml
          - name: vets-service
            valuesFile: vets-service.yaml
          - name: visits-service
            valuesFile: visits-service.yaml
          - name: admin-server
            valuesFile: admin-server.yaml
          - name: genai-service
            valuesFile: genai-service.yaml
  template:
    metadata:
      name: "petclinic-{{name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Goodnessoj/petclinic-Infra.git
        targetRevision: main
        path: helm/petclinic-service
        helm:
          releaseName: "{{name}}"
          valueFiles:
            - ../../helm-values/dev.yaml
            - "../../helm-values/{{valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: petclinic-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
