nameOverride: config-server

image:
  tag: "48a9077"
  pullPolicy: IfNotPresent

service:
  port: 8888
  targetPort: 8888

env:
  SPRING_APPLICATION_NAME: config-server
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/spring-petclinic/spring-petclinic-microservices-config
  SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
  MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT: http://zipkin.tracing:9411/api/v2/spans
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin.tracing:9411/api/v2/spans
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILESHISTOGRAM_HTTP_SERVER_REQUESTS: "true"

monitoring:
  podMonitor:
    enabled: true

pdb:
  enabled: true
